local Fluent=loadstring(game:HttpGet("https://raw.githubusercontent.com/skeptica4/Fluentvv/refs/heads/main/fluent.lua"))()
local SaveManager=loadstring(game:HttpGet("https://raw.githubusercontent.com/dawid-scripts/Fluent/master/Addons/SaveManager.lua"))()
local InterfaceManager=loadstring(game:HttpGet("https://raw.githubusercontent.com/dawid-scripts/Fluent/master/Addons/InterfaceManager.lua"))()
local P,U,R=game:GetService("Players"),game:GetService("UserInputService"),game:GetService("RunService")
local L,C=P.LocalPlayer,workspace.CurrentCamera
local G=getgenv().config or {t=false,d=false,m=false,mm=false,b=false,th=false,f=false,a=false,s=false}
getgenv().config=G
local E={Landmine=true,Man=true,Turret=true,Stonehedge=true,Sprayer=true,Sentinel=true,Refugee=true,PDC=true,MADS=true,Lifeline=true,Hallucinator=true,Governor=true,FAST_point=true,Barrier=true,Platform=true,Administrator=true}
for i=1,11 do if i~=8 then E["dead guy "..i]=true end end
local A={"Akimbo","Voltaic Impact","Gunslingers","Burst Rifle","Stonewall","Steelforge","DMR","Gift of Fire","Armour Peeler","Medical Bow","Recurve","Vitabow","Rifle","Bolter","Harpoon Gun","RPG","Rocket Stormer","Shockwave Device","Shotgun","Hallsweeper","Sprinter's Streak","SMG","Loose Trigger","Twinface","Mastermind's Rifle","Shovel","Overcharger","Rallying Cry","Machete","Handaxes","Torqueblade"}
local N,f,b,s,t,r=true,500,9999,0,nil,0
local h=function(t,c,d)Fluent:Notify({Title=t,Content=c,Duration=d or 5})end
local H=function()return L.Character and L.Character:FindFirstChild("HumanoidRootPart")end
local M=function()local m=U:GetMouseLocation();local r=workspace:Raycast(C.CFrame.Position,C:ViewportPointToRay(m.X,m.Y).Direction*1000);return r and r.Position end
local W=function()local c=L.Character;if not c then return end;for _,i in pairs(c:GetChildren())do if i:IsA("Tool")and table.find(A,i.Name)then return i.Name end end end
local g=function(o)for _,v in pairs({o,unpack(o:GetDescendants())})do for n,v in pairs(v:GetAttributes())do if n:lower():find("ammo")and typeof(v)=="number"then return v,v,n end end end end
local m=function(o,n)local a=o:GetAttributes();return a["Max"..n]or a[n.."Max"]or a["MaxAmmo"]or 30 end
local F=function()local c=L.Character;local h=H();if not h or tick()-r<.1 then return end;r=tick();local t=c:FindFirstChildOfClass("Tool");if not t or not table.find(A,t.Name)then return end;for _,v in pairs({t,unpack(t:GetDescendants())})do for n,v in pairs(v:GetAttributes())do if n:lower():find("ammo")and typeof(v)=="number"then v:SetAttribute(n,m(v,n))end end end;local u=c:FindFirstChildOfClass("Humanoid");if u then for _,t in pairs(u:GetPlayingAnimationTracks())do if t.Name:lower():find("reload")then t:Stop();t.TimePosition=t.Length end end end;if G.f then h("Fast Reload","Weapon reloaded",1)end end
local S=function()local c=L.Character;if not c then return end;local t=c:FindFirstChildOfClass("Tool");if not t or not table.find(A,t.Name)then return end;local a,o,n=g(t);if a and a<=math.floor(m(o,n)*.3)then F()end end
local T=function(m)local c=L.Character;if not t or not c or not c:FindFirstChild(t)then h("Error","No weapon detected",3);return end;local g=c[t];local s={infinite={firerate=f,ammo=999,reload=.1},fast_reload={firerate=math.min(f,150),reload=.1},balanced={firerate=math.min(f,100),reload=.5},custom={firerate=f}};local s=s[m]or s.custom;g:SetAttribute("Firerate",s.firerate);g:SetAttribute("BulletSpeed",b);g:SetAttribute("Spread",s);if s.ammo then g:GetAttributeChangedSignal("Ammo"):Connect(function()g:SetAttribute("Ammo",s.ammo)end);g:SetAttribute("Ammo",s.ammo)end;if s.reload then g:SetAttribute("ReloadTime",s.reload)end;if m=="fast_reload"or m=="balanced"then G.f=true;if m=="balanced"then G.s=true end end;h("Gun Modified","Modified "..t.." ("..m..")",3)end
local D=function()local h=H();if not h then return end;local p=h.Position;local f=h.CFrame.LookVector;for _,n in ipairs(workspace:GetChildren())do if n:IsA("Model")and not E[n.Name]and not P:GetPlayerFromCharacter(n)then local u=n:FindFirstChildOfClass("Humanoid");local p=n.PrimaryPart or n:FindFirstChild("HumanoidRootPart");if u and p and u.Health>0 then local d=n.Name=="Tank"and 13 or 5.7;n:SetPrimaryPartCFrame(CFrame.new(p+f*d)*CFrame.Angles(0,h.Orientation.Y,0))end end end end
local L=function()local l=workspace:FindFirstChild("Landmine");if l then l:Destroy();h("System","Landmine removed",4)end end
local B=function()local q=false;U.InputBegan:Connect(function(i)if i.KeyCode==Enum.KeyCode.Q then q=true end end);U.InputEnded:Connect(function(i)if i.KeyCode==Enum.KeyCode.Q then q=false end end);R.Heartbeat:Connect(function()if not G.b or not q then return end;local p=M();local x=workspace:FindFirstChild("luxsncc");local o=x and x:FindFirstChild("Bolter");if p and o and o:FindFirstChild("VerifyCoinHit")then o.VerifyCoinHit:FireServer(p)end end)end
local K=function()local d,s=false,0;U.InputBegan:Connect(function(i)if i.KeyCode==Enum.KeyCode.Semicolon then d=true end end);U.InputEnded:Connect(function(i)if i.KeyCode==Enum.KeyCode.Semicolon then d=false end end);R.Heartbeat:Connect(function(dt)if not G.mm or not d then return end;s=s+dt;if s<.1 then return end;s=0;local p=M();local m=L.Backpack:FindFirstChild("Mercy Kill")or(L.Character and L.Character:FindFirstChild("Mercy Kill"));if p and m then m.VerifyHit:FireServer(nil,p)end end)end
local A=function()getgenv().AutoDetectWeapon_Fluent=true;task.spawn(function()while getgenv().AutoDetectWeapon_Fluent do local w=W();if w~=t then t=w;if N then h("Weapon Detected","Current: "..(t or"None"),2)end end;task.wait(1)end end)end
local R=function()local T,d=0,0;R.Heartbeat:Connect(function(dt)if G.t and G.th then T=T+dt;if T>=.1 then T=0;D()end end;if G.d then d=d+dt;if d>=.5 then d=0;L()end end;if G.a then S()end end)end
U.InputBegan:Connect(function(i,g)if g then return end;if i.KeyCode==Enum.KeyCode.F1 then G.th=not G.th;h("System","Teleport handling "..(G.th and"enabled"or"disabled"),3)elseif i.KeyCode==Enum.KeyCode.R and G.f then F()elseif i.KeyCode==Enum.KeyCode.Semicolon and G.m and not G.mm then local h=H();local m=L.Backpack:FindFirstChild("Mercy Kill");if h and m then for i=1,3 do m.VerifyHit:FireServer(nil,h.Position);task.wait(.17)end end end end)
local W=Fluent:CreateWindow({Title="Fluent "..Fluent.Version,SubTitle="by dawid",TabWidth=160,Size=UDim2.fromOffset(580,460),Acrylic=false,Theme="Aqua",MinimizeKey=Enum.KeyCode.LeftControl})
local T={Main=W:AddTab({Title="Main",Icon="code-2"}),GunMod=W:AddTab({Title="Gun Mod",Icon="target"}),Misc=W:AddTab({Title="Miscellaneous",Icon="plus-circle"}),Settings=W:AddTab({Title="Settings",Icon="settings"})}
SaveManager:SetLibrary(Fluent);InterfaceManager:SetLibrary(Fluent);SaveManager:IgnoreThemeSettings();InterfaceManager:SetFolder("FluentScriptHub");SaveManager:SetFolder("FluentScriptHub/specific-game");InterfaceManager:BuildInterfaceSection(T.Settings);SaveManager:BuildConfigSection(T.Settings)
local a=function(t,n,d,c)return t:AddToggle(n,{Title=d,Default=c or false}):OnChanged(c)end
local b=function(t,n,d,c)t:AddButton({Title=n,Description=d,Callback=c})end
a(T.Main,"Tp","Teleport NPCs",false,function(v)G.t=v end)
a(T.Main,"Mk","Enable Mercy Kill",false,function(v)G.m=v;if v and G.mm then G.mm=false;T.Main:SetValue("Mmk",false)end end)
a(T.Main,"Mmk","Enable Mouse Mercy Kill",false,function(v)G.mm=v;if v then if G.m then G.m=false;T.Main:SetValue("Mk",false)end;h("Mercy Kill Mouse","Hold semicolon to fire at mouse",4)end end)
T.GunMod:AddSection("Weapon Detection");a(T.GunMod,"Ad","Show Auto-Detect Notifications",true,function(v)N=v end)
T.GunMod:AddSection("Weapon Configuration");for _,i in pairs({{n="Fr",d="Firerate",v="f"},{n="Bs",d="Bullet Speed",v="b"},{n="Sp",d="Spread",v="s"}})do T.GunMod:AddInput(i.n,{Title=i.d,Default=tostring(_G[i.v]),Numeric=true,Placeholder="Enter "..i.d}):OnChanged(function(v)local n=tonumber(v)if n then _G[i.v]=n end end)end
T.GunMod:AddSection("Reload System");a(T.GunMod,"Fr","Enable Fast Reload (Press R)",false,function(v)G.f=v;if v then h("Fast Reload","Press R to reload",3)end end);a(T.GunMod,"Ar","Enable Smart Auto-Reload",false,function(v)G.a=v;if v then h("Auto Reload","Auto-reload when low",3)end end)
T.GunMod:AddSection("Gun Modification");for _,m in pairs({{"Infinite Ammo Mode","Full infinite ammo + high firerate (SUSPICIOUS)","infinite"},{"Fast Reload Mode","Balanced stats + fast reload (RECOMMENDED)","fast_reload"},{"Balanced Mode","Conservative stats + smart features","balanced"},{"Custom Stats Only","Apply custom stats without ammo changes","custom"}})do b(T.GunMod,m[1],m[2],function()T(m[3])end)end
b(T.GunMod,"InfAmmo Only","Only enable infinite ammo",function()local c=L.Character;if not t or not c or not c:FindFirstChild(t)then h("Error","No weapon found",3)return end;local g=c[t];g:GetAttributeChangedSignal("Ammo"):Connect(function()g:SetAttribute("Ammo",999)end);g:SetAttribute("Ammo",999);h("InfAmmo Enabled","Infinite Ammo for "..t,3)end)
a(T.Misc,"Lm","Destroy Landmine",false,function(v)G.d=v end);a(T.Misc,"Bc","Bolter Coin Hit",false,function(v)G.b=v end)
T.Misc:AddSection("Teleportation");for _,p in pairs({{"Teleport to Lobby","Teleports to lobby ingame",function()local h=H();if h then h.CFrame=CFrame.new(-3,-101.5,-12.5);h("System","Teleported to lobby",4)end end},{"Teleport to Map","Teleports player to map",function()local c=L.Character;if c then local h=c:WaitForChild("HumanoidRootPart");h.CFrame=workspace.Map.PlayerSpawns.SpawnLocation.CFrame+Vector3.new(0,3,0);h("System","Teleported to map",4)end end}})do b(T.Misc,p[1],p[2],p[3])end
T.Misc:AddSection("Utility");b(T.Misc,"Dev Tools","Developer tools and utilities",function()W:Dialog({Title="Developer Tools",Buttons={{Title="Dark Dex",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/skeptica4/aaaaaaaaaaaaaa/main/darkdex"))()end},{Title="Remote Spy",Callback=function()loadstring(game:HttpGet("https://github.com/exxtremestuffs/SimpleSpySource/raw/master/SimpleSpy.lua"))()end},{Title="Close",Callback=function()end}}})end)
h("Fluent","Script loaded with Fast Reload system",5);W:SelectTab(1);R();B();K();A();SaveManager:LoadAutoloadConfig()
